"""Train/test leakage audit and group recovery.

This module is the reason the project exists in the form it does.

Published static-ASL results cluster suspiciously around 99.9%. The cause is
not clever architecture, it is that the standard corpora are continuous webcam
captures split at random: frame 1041 lands in train, frame 1042 lands in test,
and the classifier scores a perfect mark for recognising a shirt collar. The
Sign Language MNIST test split is generated by augmenting the same base
photographs used for train, so it is leaky by construction.

Two tools here, both operating on a 64-bit difference hash:

  `recover_groups`  - build a near-duplicate graph over a corpus and take its
                      connected components as capture sessions. Splitting on
                      those components removes frame-level leakage, which is the
                      dominant leak in continuous-capture corpora.

                      Read the limitation in that function's docstring before
                      calling the result "signer-independent". It is not.

  `audit`           - given an already-split manifest, report how much of the
                      test set has a near-duplicate sitting in train. This
                      number is the headline honesty metric. `--purge` drops
                      the contaminated test rows.

Candidate generation uses banded hashing with a pigeonhole guarantee rather
than the O(n^2) all-pairs scan: splitting the 64-bit hash into B equal bands,
any pair within Hamming distance B-1 must agree exactly on at least one band.
So bucketing by band value finds every true match with no false negatives,
while touching a small fraction of the pairs.
"""

from __future__ import annotations

import json
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np
from PIL import Image

HASH_BITS = 64
_POPCOUNT8 = np.array([bin(i).count("1") for i in range(256)], dtype=np.uint8)


# --- hashing -----------------------------------------------------------------

def dhash(path: str | Path, size: int = 8) -> int:
    """64-bit difference hash: grey, resize to (size+1, size), compare columns.

    Robust to resolution, mild compression, and small brightness shifts, which
    is exactly the family of differences that separates two frames of the same
    continuous capture.
    """
    with Image.open(path) as im:
        g = im.convert("L").resize((size + 1, size), Image.Resampling.LANCZOS)
    a = np.asarray(g, dtype=np.int16)
    bits = (a[:, 1:] > a[:, :-1]).ravel()
    return int(np.packbits(bits).view(">u8")[0])


def hash_many(paths: Sequence[str], workers: int = 0) -> np.ndarray:
    """Hash a list of images, returning a uint64 array aligned with `paths`.

    Threads, not processes. The work is JPEG decoding, which happens in Pillow's
    C decoders with the GIL released, so threads get the parallelism anyway - and
    unlike a process pool they do not need an importable `__main__`, which is
    what makes this work unchanged from a notebook cell or a piped script.
    """
    workers = workers or min(8, (len(paths) // 500) + 1)
    if workers <= 1:
        return np.array([dhash(p) for p in paths], dtype=np.uint64)
    with ThreadPoolExecutor(max_workers=workers) as ex:
        return np.fromiter(ex.map(dhash, paths), dtype=np.uint64, count=len(paths))


def hamming(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Bitwise Hamming distance between two uint64 arrays, elementwise."""
    x = np.bitwise_xor(np.asarray(a, dtype=np.uint64), np.asarray(b, dtype=np.uint64))
    return _POPCOUNT8[x.view(np.uint8).reshape(-1, 8)].sum(axis=1).astype(np.int16)


def _bands(h: np.ndarray, n_bands: int) -> np.ndarray:
    """Split each uint64 into `n_bands` equal slices, as a (len(h), n_bands) array."""
    width = HASH_BITS // n_bands
    mask = np.uint64((1 << width) - 1)
    return np.stack([(h >> np.uint64(i * width)) & mask for i in range(n_bands)], axis=1)


def candidate_pairs(h: np.ndarray, max_dist: int) -> Iterable[tuple[int, int]]:
    """Yield index pairs that could be within `max_dist` bits.

    Pigeonhole: with B = max_dist + 1 bands, a pair differing in at most
    max_dist bits leaves at least one band untouched, so it collides there.
    No true match is missed. Buckets larger than `cap` are dropped - a bucket
    that big means a flat or near-black band shared by thousands of images,
    which carries no identity signal and would blow up quadratically.
    """
    n_bands = max(2, max_dist + 1)
    cap = 4000
    for col in _bands(h, n_bands).T:
        order = np.argsort(col, kind="stable")
        vals = col[order]
        starts = np.flatnonzero(np.r_[True, vals[1:] != vals[:-1]])
        for s, e in zip(starts, np.r_[starts[1:], len(vals)]):
            if e - s < 2 or e - s > cap:
                continue
            idx = order[s:e]
            for i in range(len(idx)):
                for j in range(i + 1, len(idx)):
                    yield int(idx[i]), int(idx[j])


# --- union-find --------------------------------------------------------------

class _DSU:
    def __init__(self, n: int) -> None:
        self.p = list(range(n))

    def find(self, x: int) -> int:
        while self.p[x] != x:
            self.p[x] = self.p[self.p[x]]
            x = self.p[x]
        return x

    def union(self, a: int, b: int) -> None:
        ra, rb = self.find(a), self.find(b)
        if ra != rb:
            self.p[rb] = ra


# --- group recovery ----------------------------------------------------------

def recover_groups(rows: list[dict], max_dist: int = 6, workers: int = 0) -> list[dict]:
    """Overwrite `group` with near-duplicate connected components, per source.

    What this recovers: **capture sessions**. Runs of frames showing the same
    person holding the same handshape, which is what a continuous webcam capture
    produces and what a random split scatters across train and test. On
    `asl_alphabet` and friends this is the entire leak, and splitting on these
    components removes it.

    What this does NOT recover: **signer identity**. If a corpus has one shot per
    person per class, there are no near-duplicates linking that person's images,
    and the method has nothing to work with.

    Measured on `sl_digits`, the one corpus here with recoverable ground-truth
    signer ids (2062 images, 217 signers, one shot per person per digit):

        max_dist   components   signers fragmented across components
             2          2021                     217 / 217
             6           953                     211 / 217
            10           141                      88 / 217
            12            48                      37 / 217

    Every signer is fragmented at usable thresholds, and raising the threshold
    until they are not simply collapses the corpus into a handful of blobs. So a
    group split built on recovered components is honest about frames and silent
    about signers.

    That limitation is the reason the headline metric in this project is
    cross-corpus evaluation rather than an in-corpus group split: training on one
    corpus and testing on another guarantees signer disjointness by construction,
    without needing to recover who anyone is.

    Components are computed within a source, never across, because a match across
    two corpora is a cross-corpus leak the audit should *report* rather than a
    reason to merge groups.

    Mutates and returns `rows`, and stashes the hash on each row so `audit` does
    not have to recompute it.
    """
    by_source: dict[str, list[int]] = defaultdict(list)
    for i, r in enumerate(rows):
        by_source[r["source"]].append(i)

    for source, idxs in by_source.items():
        paths = [rows[i]["path"] for i in idxs]
        h = hash_many(paths, workers)
        for i, hv in zip(idxs, h):
            rows[i]["dhash"] = int(hv)

        dsu = _DSU(len(idxs))
        n_edges = 0
        for a, b in candidate_pairs(h, max_dist):
            if hamming(h[a : a + 1], h[b : b + 1])[0] <= max_dist:
                dsu.union(a, b)
                n_edges += 1

        comps: dict[int, int] = {}
        for local, gi in enumerate(idxs):
            root = dsu.find(local)
            cid = comps.setdefault(root, len(comps))
            rows[gi]["group"] = f"{source}/dup{cid:06d}"
        print(f"[groups] {source}: {len(idxs)} imgs -> {len(comps)} components "
              f"({n_edges} near-dup edges, d<={max_dist})")
    return rows


# --- audit -------------------------------------------------------------------

def audit(rows: list[dict], max_dist: int = 6, workers: int = 0) -> dict:
    """Measure contamination of every non-train split by the train split.

    Returns a report dict and marks each contaminated row with
    `leak_dist` / `leak_of` so `purge` can act on it.
    """
    need = [r for r in rows if "dhash" not in r]
    if need:
        for r, hv in zip(need, hash_many([r["path"] for r in need], workers)):
            r["dhash"] = int(hv)

    train = [r for r in rows if r["split"] == "train"]
    if not train:
        raise ValueError("manifest has no train rows - assign splits first")
    th = np.array([r["dhash"] for r in train], dtype=np.uint64)

    report: dict = {"max_dist": max_dist, "n_train": len(train), "splits": {}}
    for split in sorted({r["split"] for r in rows} - {"train", ""}):
        probe = [r for r in rows if r["split"] == split]
        ph = np.array([r["dhash"] for r in probe], dtype=np.uint64)

        # Index train by band, then look each probe up in the same bands.
        n_bands = max(2, max_dist + 1)
        width = HASH_BITS // n_bands
        mask = np.uint64((1 << width) - 1)
        buckets = [defaultdict(list) for _ in range(n_bands)]
        for i, hv in enumerate(th):
            for b in range(n_bands):
                buckets[b][int((hv >> np.uint64(b * width)) & mask)].append(i)

        exact = near = 0
        per_source: dict[str, dict[str, int]] = defaultdict(lambda: {"n": 0, "leaked": 0})
        for j, r in enumerate(probe):
            per_source[r["source"]]["n"] += 1
            cands: set[int] = set()
            for b in range(n_bands):
                cands.update(buckets[b].get(int((ph[j] >> np.uint64(b * width)) & mask), ()))
            if not cands:
                continue
            ci = np.fromiter(cands, dtype=np.int64)
            d = hamming(th[ci], np.full(len(ci), ph[j], dtype=np.uint64))
            k = int(d.argmin())
            if d[k] <= max_dist:
                near += 1
                exact += int(d[k] == 0)
                per_source[r["source"]]["leaked"] += 1
                r["leak_dist"] = int(d[k])
                r["leak_of"] = train[int(ci[k])]["path"]

        n = len(probe)
        report["splits"][split] = {
            "n": n,
            "exact_duplicates": exact,
            "near_duplicates": near,
            "leak_rate": round(near / n, 4) if n else 0.0,
            "by_source": {s: {**v, "leak_rate": round(v["leaked"] / v["n"], 4)}
                          for s, v in per_source.items()},
        }
        print(f"[audit] {split}: {near}/{n} ({near / max(n, 1):.1%}) have a train "
              f"near-duplicate within {max_dist} bits ({exact} pixel-identical)")
    return report


def purge(rows: list[dict]) -> list[dict]:
    """Drop rows the audit flagged as contaminated. Train rows are never dropped."""
    keep = [r for r in rows if r["split"] == "train" or "leak_dist" not in r]
    print(f"[purge] {len(rows) - len(keep)} contaminated eval rows removed")
    return keep


def main(argv: list[str] | None = None) -> int:
    import argparse

    from . import sources

    ap = argparse.ArgumentParser(description="near-duplicate audit and group recovery")
    ap.add_argument("cmd", choices=["groups", "audit"])
    ap.add_argument("manifest", type=Path)
    ap.add_argument("--out", type=Path, default=None, help="rewrite the manifest here")
    ap.add_argument("--report", type=Path, default=Path("runs/leakage_report.json"))
    ap.add_argument("--max-dist", type=int, default=6)
    ap.add_argument("--purge", action="store_true", help="drop contaminated eval rows")
    ap.add_argument("--workers", type=int, default=0)
    a = ap.parse_args(argv)

    rows = sources.read_manifest(a.manifest)
    if a.cmd == "groups":
        recover_groups(rows, a.max_dist, a.workers)
    else:
        rep = audit(rows, a.max_dist, a.workers)
        a.report.parent.mkdir(parents=True, exist_ok=True)
        a.report.write_text(json.dumps(rep, indent=2))
        print(f"[ok] report -> {a.report}")
        if a.purge:
            rows = purge(rows)

    sources.write_manifest(
        [{k: r[k] for k in sources.MANIFEST_COLS} for r in rows],
        a.out or a.manifest,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
